# Dev 环境覆盖值
# CI 会自动更新各服务的 tag（commit SHA）
environment: dev
services:
  frontend:
    tag: ba9c2a4
  user-service:
    tag: ba9c2a4
  product-service:
    tag: ba9c2a4
  order-service:
    tag: ba9c2a4
