# Dev 环境覆盖值
# CI 会自动更新各服务的 tag（commit SHA）
environment: dev
services:
  frontend:
    tag: 1bdd860
  user-service:
    tag: 1bdd860
  product-service:
    tag: 1bdd860
  order-service:
    tag: 1bdd860
